### ISSUE TITLE
A detail mistake in loading config process

### ISSUE THREAD

**Issue by XingtongGe** [OutofAi/2D-Gaussian-Splatting#4]
![image](https://github.com/OutofAi/2D-Gaussian-Splatting/assets/58927343/b25f1616-1afa-449d-abf5-195edcc67818)

Hi, thanks for your amazing work! And I've noticed that there's a detail mistake in loading config process. 

The code in loading gauss_threshold should be 
```
gauss_threshold = config["gaussian_threshold"]
```

**Comment by OutofAi** [comment]
Thanks for pointing it out, should be fixed now 
https://github.com/OutofAi/2D-Gaussian-Splatting/commit/3d4db52f57e140d7f00fd0de30bfb70db8335692
